config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "homepage#show"

  namespace :loans do
    resource :borrower_step, only: [:show, :create], controller: "borrower_step"
    resource :isbn_step,     only: [:show, :create], controller: "isbn_step"
  end

  resources :loans, only: [:index, :new, :create, :destroy]
  resources :borrowed_books, only: [:index]

  resource :settings, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/loan.rb
class Loan < ApplicationRecord
  belongs_to :lender, class_name: "User"
  belongs_to :borrower, class_name: "User"

  validates :title, presence: :true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :loaned_books, foreign_key: :lender_id, class_name: "Loan"
  has_many :borrowed_books, foreign_key: :borrower_id, class_name: "Loan"

  def initials
    return email.first.upcase unless full_name.present?

    full_name.split[0..1].map(&:first).join.upcase
  end

  def full_name
    @full_name || email.match(/([^@]+)@/)[1].capitalize
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  def display_menu?
    !controller_name.include?('step') && \
    !controller_name.include?('settings') && \
    !action_name.include?('new')
  end
  helper_method :display_menu?

end

app/controllers/borrowed_books_controller.rb
class BorrowedBooksController < ApplicationController
  def index
    @borrowed_books = current_user.borrowed_books
  end
end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController
  def show
  end
end

app/controllers/loans/borrower_step_controller.rb
class Loans::BorrowerStepController < ApplicationController
  def show
    @users = User.where.not(id: current_user.id)

    render 'loans/borrower_step'
  end

  def create
    session[:loan] = {}
    session[:loan]["borrower_id"] = params[:user]

    redirect_to loans_isbn_step_path
  end
end

app/controllers/loans/isbn_step_controller.rb
class Loans::IsbnStepController < ApplicationController
  def show
    render 'loans/isbn_step'
  end

  def create
    session[:loan]["isbn"] = params[:isbn]

    redirect_to new_loan_path
  end
end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
  def new
    @isbn = session[:loan]["isbn"]

    @loan = Loan.new(book_params_from_openlibrary.merge(book_params_from_google.compact))
    @loan.lender = current_user

    redirect_to loans_isbn_step_path(retry: true, isbn: @isbn) if @loan.invalid?
  end

  def create
    @loan = Loan.new(loan_params)
    @loan.lender = current_user

    @loan.save

    respond_to do |format|
      format.turbo_stream do
        # render turbo_stream: turbo_stream.append(:loans, partial: "loans/loan", locals: { loan: @loan })
        # @loan.broadcast_append_to current_user, :loans, partial: "loans/loan", locals: { loan: @loan }
        @loan.broadcast_append_to(@loan.borrower, :borrowed_books,
          partial: "borrowed_books/borrowed_book",
          locals: { borrowed_book: @loan },
          target: "borrowed_books"
        )
        redirect_to loans_path
      end

      format.html { redirect_to loans_path}
    end
  end

  def index
    @loans = current_user.loaned_books
  end

  def destroy
    @loan = Loan.find(params[:id])
    @loan.destroy

    respond_to do |format|
      format.turbo_stream do
        # render turbo_stream: turbo_stream.remove(@loan)
        @loan.broadcast_remove_to current_user, :loans
        @loan.broadcast_remove_to @loan.borrower, :borrowed_books
      end

      format.html { redirect_to loans_path }
    end

  end

  private

  def loan_params
    params.require(:loan).permit(:borrower_id, :isbn, :title, :author, :picture_url)
  end

  def book_params_from_google
    response = HTTParty.get("https://www.googleapis.com/books/v1/volumes?q=isbn:#{@isbn}&key=#{ENV["GOOGLE_BOOK_API"]}")
    book_data = JSON.parse(response.body, symbolize_names: true)

    return {} if book_data[:totalItems].zero?

    book = book_data[:items].first

    {
      borrower_id: session[:loan]["borrower_id"],
      isbn:        @isbn,
      title:       book.dig(:volumeInfo, :title),
      author:      book.dig(:volumeInfo, :authors)&.to_sentence,
      picture_url: book.dig(:imageLinks, :medium)
    }
  end

  def book_params_from_openlibrary
    response = HTTParty.get("https://openlibrary.org/api/volumes/brief/isbn/#{@isbn}.json")
    book_data = JSON.parse(response.body, symbolize_names: true)

    return {} if !book_data.present?

    book = book_data[:records].values.first[:data]

    {
      borrower_id: session[:loan]["borrower_id"],
      isbn: @isbn,
      title: book[:title],
      author: book[:authors].map { |author| author[:name] }.to_sentence,
      picture_url: book.dig(:cover, :medium) || ""
    }
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/greetings_helper.rb
module GreetingsHelper
  def greetings
    values = ["night", "morning", "afternoon", "evening"].map { |value| t("greetings.#{value}") }

    tag.span("", data: {
      controller: "greetings",
      greetings_target: "timedResponse", greetings_greetings_value: values
    })
  end
end

app/helpers/user_helper.rb
module UserHelper
  def user_select(user)
    tag.div(user.initials, class: "user-avatar") + tag.div(user.full_name)
  end
end

app/views/borrowed_books/_borrowed_book.html.erb
<section id="<%= dom_id(borrowed_book) %>" class="loan">
  <%= image_tag borrowed_book.picture_url.presence || "", title: borrowed_book.title %>

  <div class="right">
    <p><%= t(".borrowed_from") %> <span class="borrower"><%= borrowed_book.lender.full_name %></span></p>
    <div class="details">
      <div class="title"><%= borrowed_book.title %></div>
      <div class="author"><%= borrowed_book.author %></div>
    </div>
  </div>
</section>

app/views/borrowed_books/index.html.erb
<h2><%= t(".title") %></h2>

<%= turbo_stream_from current_user, :borrowed_books %>
<div id="borrowed_books">
  <%= render partial: "borrowed_books/borrowed_book", collection: @borrowed_books %>
</div>


<% if @borrowed_books.empty? %>
  <p><%= t(".no_data") %></p>
<% end %>

app/views/homepage/show.html.erb
<h2 class="greetings">
  <%= greetings %>, <br>
  <%= current_user.full_name %>
</h2>

<div style="margin-top: 3rem; display: inline-block">
  <%= link_to loans_borrower_step_path, class: "action" do %>
    <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M12 6v6m0 0v6m0-6h6m-6 0H6"></path></svg>
    <span><%=  t(".loan_a_book") %></span>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioshare</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user && display_menu? %>
      <%= link_to current_user.initials, settings_path, class: "user-avatar" %>
      <nav>
        <ul>
          <li><%= link_to_unless_current(t(".home"), root_path){ |name| tag.p name } %></li>
          <li><%= link_to_unless_current(t(".loans"), loans_path){ |name| tag.p name } %></li>
          <li><%= link_to_unless_current(t(".borrowed_books"), borrowed_books_path){ |name| tag.p name } %></li>
        </ul>
      </nav>
    <% end %>

    <p class="alert"><%= alert %></p>

    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/loans/_loan.html.erb
<section id="<%= dom_id(loan) %>" class="loan">
  <%= image_tag loan.picture_url.presence || "", title: loan.title %>

  <div class="right">
    <p><%= t(".loaned_to") %> <span class="borrower"><%= loan.borrower.full_name %></span></p>
    <%= link_to loan_path(loan), method: :delete, class: "action" do %>
      <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M5 13l4 4L19 7"></path></svg>
      <span><%= t(".i_got_it_back") %><span>
    <% end %>
    <div class="details">
      <div class="title"><%= loan.title %></div>
      <div class="author"><%= loan.author %></div>
    </div>
  </div>
</section>

app/views/loans/borrower_step.html.erb
<%= link_to root_path, class: "back-link" do %>
  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
<% end %>

<h2 style="margin: 1rem 0">
  <%= t(".title") %>
</h2>

<%= form_tag loans_borrower_step_path,
  data: { controller: "form", action: "change->form#submit" } do %>

  <% @users.each do |user| %>
    <div class="user-select">
      <%= radio_button_tag(:user, user.id) %>
      <%= label_tag(dom_id(user), user_select(user)) %>
    </div>
  <% end %>
<% end %>

app/views/loans/index.html.erb
<h2><%= t(".title") %></h2>

<%= turbo_stream_from current_user, :loans %>
<div id="loans">
  <%= render partial: "loans/loan", collection: @loans %>
</div>

<% if @loans.empty? %>
  <p><%= t(".no_data") %></p>

  <%= link_to t(".loan_a_book"), loans_borrower_step_path, class: 'action', style: "margin-top: 2rem" %>
<% end %>

app/views/loans/isbn_step.html.erb
<%= link_to loans_borrower_step_path, class: "back-link" do %>
  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
<% end %>

<h2 style="margin-top: 1rem; display: flex">
  <%= t(".title") %>
  <svg aria-hidden="true" focusable="false" data-prefix="fal" data-icon="barcode-read" class="svg-inline--fa fa-barcode-read fa-w-20" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 640 512"><path fill="currentColor" d="M152 0H8C3.6 0 0 3.6 0 8v152c0 4.4 3.6 8 8 8h16c4.4 0 8-3.6 8-8V32h120c4.4 0 8-3.6 8-8V8c0-4.4-3.6-8-8-8zm0 480H32V352c0-4.4-3.6-8-8-8H8c-4.4 0-8 3.6-8 8v152c0 4.4 3.6 8 8 8h144c4.4 0 8-3.6 8-8v-16c0-4.4-3.6-8-8-8zM632 0H488c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8h120v128c0 4.4 3.6 8 8 8h16c4.4 0 8-3.6 8-8V8c0-4.4-3.6-8-8-8zm0 344h-16c-4.4 0-8 3.6-8 8v128H488c-4.4 0-8 3.6-8 8v16c0 4.4 3.6 8 8 8h144c4.4 0 8-3.6 8-8V352c0-4.4-3.6-8-8-8zM152 96h-48c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V104c0-4.4-3.6-8-8-8zm336 320h48c4.4 0 8-3.6 8-8V104c0-4.4-3.6-8-8-8h-48c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8zM408 96h-48c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8h48c4.4 0 8-3.6 8-8V104c0-4.4-3.6-8-8-8zm-192 0h-16c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8h16c4.4 0 8-3.6 8-8V104c0-4.4-3.6-8-8-8zm64 0h-16c-4.4 0-8 3.6-8 8v304c0 4.4 3.6 8 8 8h16c4.4 0 8-3.6 8-8V104c0-4.4-3.6-8-8-8z"></path></svg>
</h2>

<div data-controller="barcode-scanner">
  <div data-barcode-scanner-target="camArea" id="cam-area"></div>
  <%= form_tag loans_isbn_step_path, data: { barcode_scanner_target: "form" } do %>
    <%= hidden_field_tag :isbn, '', data: { barcode_scanner_target: "input"} %>
  <% end %>
</div>

<% if params[:retry] == 'true' %>
  <p><%= t(".retry") %></p>
  <p>ISBN <strong style="font-family: mono"><%= params[:isbn] %></strong> not found.</p>
<% end %>

app/views/loans/new.html.erb
<%= link_to loans_isbn_step_path, class: "back-link" do %>
  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
<% end %>

<h2 style="margin: 1rem 0">
  <%= t(".title") %>
</h2>

<%= form_with model: @loan, style: "margin-top: 2rem" do |f| %>
  <%= f.hidden_field :borrower_id, value: @loan.borrower_id %>
  <%= f.hidden_field :isbn, value: @loan.isbn %>
  <%= f.hidden_field :title, value: @loan.title %>
  <%= f.hidden_field :author, value: @loan.author %>
  <%= f.hidden_field :picture_url, value: @loan.picture_url %>

  <section class="loan">
    <%= image_tag @loan.picture_url.presence || "", title: @loan.title %>

    <div class="right">
      <p><%= t(".loan_to?_html", name: @loan.borrower.full_name) %></p>

      <%= f.submit t('.create'), class: 'action' %>

      <div class="details">
        <div class="title"><%= @loan.title %></div>
        <div class="author"><%= @loan.author %></div>
      </div>
    </div>
  </section>

<% end %>

app/views/settings/show.html.erb
<%= link_to root_path, class: "back-link" do %>
  <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M9.707 16.707a1 1 0 01-1.414 0l-6-6a1 1 0 010-1.414l6-6a1 1 0 011.414 1.414L5.414 9H17a1 1 0 110 2H5.414l4.293 4.293a1 1 0 010 1.414z" clip-rule="evenodd"></path></svg>
<% end %>

<div class="profile" style="margin: 1rem 0">
  <header>
    <h2><%= current_user.full_name %></h2>
    <div class="user-avatar"><%= current_user.initials %></div>
  </header>
  <span class="email"><%= current_user.email %></span>
</div>



<%= link_to t('devise.sessions.sign_out'), destroy_user_session_path, method: :delete, class: 'action link' %>

app/views/users/new.html.erb
<%= form_with model: @user do |f|%>
  <%= f.label :full_name %>
  <%= f.text_field :full_name, :placeholder => "ie. Mark Smith" %>
<% end %>